import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'

export default function Home() {
  return (
    <div className={styles.container}>
      <style jsx>
        {`
        h2 {
          font-size: 38px;
        }
        h3 {
          font-size: 25px;
        }
        `}
      </style>
      <Head>
        <title>BlogBuster</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="keywords" content="next, nextJs, Blogs, blogbuster, blogbuster blog" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>
          BlogBuster
        </h1>

        <Image className={styles.myImg} src="/home.jpg" alt="blogbuster" width={200} height={200}/>

        <p className={styles.description}>
          Bust your bugs with BlogBuster
        </p>

        <div className="blogs">
          <h2>Latest blogs</h2>
          <div className="blogItem">
            <h3>How to learn JavaScript in 2023</h3>
            <p>JavaScript is the language used to design logic for the web</p>
          </div>
          <div className="blogItem">
            <h3>How to learn JavaScript in 2023</h3>
            <p>JavaScript is the language used to design logic for the web</p>
          </div>
          <div className="blogItem">
            <h3>How to learn JavaScript in 2023</h3>
            <p>JavaScript is the language used to design logic for the web</p>
          </div>
        </div>
      </main>

      <footer className={styles.footer}>
      </footer>
    </div>
  )
}
